package ldapschemaparser

var keywordTypeLookupMap = map[string]int{
	"APPLIES":  NOIDS_ATTR_KEYWORD,
	"AUX":      NOIDS_ATTR_KEYWORD,
	"DESC":     QSTRING_ATTR_KEYWORD,
	"EQUALITY": NOIDS_ATTR_KEYWORD,
	"FORM":     NOIDS_ATTR_KEYWORD,
	"MAY":      NOIDS_ATTR_KEYWORD,
	"MUST":     NOIDS_ATTR_KEYWORD,
	"NAME":     QSTRINGS_ATTR_KEYWORD,
	"NOT":      NOIDS_ATTR_KEYWORD,
	"ORDERING": NOIDS_ATTR_KEYWORD,
	"SUBSTR":   NOIDS_ATTR_KEYWORD,
	"SUP":      NOIDS_ATTR_KEYWORD,
	"SYNTAX":   OIDLEN_ATTR_KEYWORD,
}
