// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package ldapschemaparser

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:5
type yySymType struct {
	yys                  int
	genericSchema        *GenericSchema
	parameterizedKeyword *ParameterizedKeyword
	text                 string
}

const SPACES = 57346
const NUMBER = 57347
const NUMERIC_OID = 57348
const KEYWORD = 57349
const X_KEYWORD = 57350
const NOIDS_ATTR_KEYWORD = 57351
const OIDLEN_ATTR_KEYWORD = 57352
const QSTRINGS_ATTR_KEYWORD = 57353
const QSTRING_ATTR_KEYWORD = 57354
const SQSTRING = 57355
const DQSTRING = 57356

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"SPACES",
	"NUMBER",
	"NUMERIC_OID",
	"KEYWORD",
	"X_KEYWORD",
	"NOIDS_ATTR_KEYWORD",
	"OIDLEN_ATTR_KEYWORD",
	"QSTRINGS_ATTR_KEYWORD",
	"QSTRING_ATTR_KEYWORD",
	"SQSTRING",
	"DQSTRING",
	"'$'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:155

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 85

var yyAct = [...]int{

	3, 29, 39, 41, 40, 43, 44, 66, 65, 55,
	18, 61, 10, 20, 21, 22, 23, 24, 25, 54,
	32, 33, 64, 34, 35, 36, 37, 45, 30, 46,
	4, 48, 27, 31, 32, 33, 62, 34, 35, 36,
	37, 32, 33, 50, 34, 35, 36, 37, 6, 5,
	53, 59, 58, 60, 57, 42, 19, 63, 11, 16,
	12, 13, 14, 15, 9, 70, 68, 8, 43, 44,
	7, 49, 71, 17, 69, 67, 47, 26, 2, 38,
	56, 52, 51, 28, 1,
}
var yyPact = [...]int{

	74, -1000, 22, 39, -1000, 62, 59, 47, 47, 48,
	-1000, -1000, 22, 22, 22, 22, 22, 48, 72, 47,
	24, -8, 51, -12, 51, 71, -1000, -1000, -1000, -1000,
	22, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 65,
	-1000, -1000, 22, -1000, -1000, -1000, -1000, -1000, 10, 0,
	-12, 22, 43, -1000, -1000, 4, 28, -1000, 3, -2,
	70, -1000, -12, 69, 22, -1000, -1000, -1000, -1000, -1000,
	31, -1000,
}
var yyPgo = [...]int{

	0, 84, 64, 12, 83, 82, 81, 4, 80, 1,
	3, 79, 0,
}
var yyR1 = [...]int{

	0, 1, 1, 12, 12, 9, 9, 9, 9, 9,
	9, 5, 5, 6, 6, 4, 4, 4, 4, 10,
	10, 8, 8, 7, 7, 11, 11, 3, 3, 3,
	3, 3, 3, 2, 2,
}
var yyR2 = [...]int{

	0, 7, 7, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 5, 1, 3, 1, 5, 1, 5, 1,
	1, 1, 3, 1, 5, 1, 4, 1, 3, 3,
	3, 3, 3, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, 4, -12, 8, 10, 9, 8, 8, -2,
	-3, 11, 13, 14, 15, 16, 12, -2, -12, 8,
	-12, -12, -12, -12, -12, -12, 5, -3, -4, -9,
	4, 9, 10, 11, 13, 14, 15, 16, -11, 10,
	-7, -10, 4, 17, 18, -10, -7, 5, -12, 6,
	-12, -5, -6, -9, 9, 9, -8, -10, -12, 8,
	-12, 7, 8, -12, 19, 5, 9, 5, -10, 5,
	-12, -9,
}
var yyDef = [...]int{

	0, -2, 3, 0, 4, 0, 0, 0, 0, 3,
	33, 27, 3, 3, 3, 3, 3, 3, 0, 4,
	0, 0, 0, 0, 0, 0, 1, 34, 28, 15,
	3, 17, 5, 6, 7, 8, 9, 10, 29, 25,
	30, 23, 3, 19, 20, 31, 32, 2, 0, 0,
	0, 3, 3, 11, 13, 0, 3, 21, 0, 4,
	0, 26, 4, 0, 3, 16, 14, 18, 22, 24,
	0, 12,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 19, 3, 3, 3,
	4, 5, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 6, 3, 7,
}
var yyTok2 = [...]int{

	2, 3, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:31
		{
			yyVAL.genericSchema = yyDollar[5].genericSchema
			yyVAL.genericSchema.NumericOID = yyDollar[3].text
			yylex.(*schemaLexer).result = yyVAL.genericSchema
		}
	case 2:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:36
		{
			yyVAL.genericSchema = yyDollar[5].genericSchema
			yyVAL.genericSchema.NumericOID = yyDollar[3].text
			yylex.(*schemaLexer).result = yyVAL.genericSchema
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:45
		{
			yyVAL.text = yyDollar[1].text
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:48
		{
			yyVAL.text = yyDollar[1].text
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:51
		{
			yyVAL.text = yyDollar[1].text
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:54
		{
			yyVAL.text = yyDollar[1].text
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:57
		{
			yyVAL.text = yyDollar[1].text
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:60
		{
			yyVAL.text = yyDollar[1].text
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:64
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, OIDsRule)
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:67
		{
			yyVAL.parameterizedKeyword = yyDollar[1].parameterizedKeyword
			yyVAL.parameterizedKeyword.addParameter(yyDollar[5].text)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:72
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, NumberIDsRule)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:75
		{
			yyVAL.parameterizedKeyword = yyDollar[1].parameterizedKeyword
			yyVAL.parameterizedKeyword.addParameter(yyDollar[3].text)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:80
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, OIDsRule)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:83
		{
			yyVAL.parameterizedKeyword = yyDollar[3].parameterizedKeyword
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:86
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, NumberIDsRule)
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:89
		{
			yyVAL.parameterizedKeyword = yyDollar[3].parameterizedKeyword
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:93
		{
			yyVAL.text = yyDollar[1].text
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:96
		{
			yyVAL.text = yyDollar[1].text
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:100
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, QuotedStringsRule)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:103
		{
			yyVAL.parameterizedKeyword = yyDollar[1].parameterizedKeyword
			yyVAL.parameterizedKeyword.addParameter(yyDollar[3].text)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:108
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, QuotedStringsRule)
		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:111
		{
			yyVAL.parameterizedKeyword = yyDollar[3].parameterizedKeyword
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:115
		{
			yyVAL.text = yyDollar[1].text
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:118
		{
			yyVAL.text = yyDollar[1].text + "{" + yyDollar[3].text + "}"
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:122
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addFlagKeywords(yyDollar[1].text)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:126
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, yyDollar[3].parameterizedKeyword)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:130
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, newParameterizedKeywordWithParameter(yyDollar[3].text, OIDWithLengthRule))
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:134
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, yyDollar[3].parameterizedKeyword)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:138
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, newParameterizedKeywordWithParameter(yyDollar[3].text, QuotedStringRule))
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:142
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, yyDollar[3].parameterizedKeyword)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:147
		{
			yyVAL.genericSchema = yyDollar[1].genericSchema
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:150
		{
			yyDollar[1].genericSchema.add(yyDollar[3].genericSchema)
			yyVAL.genericSchema = yyDollar[1].genericSchema
		}
	}
	goto yystack /* stack new state and value */
}
