// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package ldapschemaparser

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:5
type yySymType struct {
	yys                  int
	genericSchema        *GenericSchema
	parameterizedKeyword *ParameterizedKeyword
	text                 string
}

const SPACES = 57346
const NUMBER = 57347
const NUMERIC_OID = 57348
const KEYWORD = 57349
const X_KEYWORD = 57350
const NOIDS_ATTR_KEYWORD = 57351
const SQSTRING = 57352
const DQSTRING = 57353

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"SPACES",
	"NUMBER",
	"NUMERIC_OID",
	"KEYWORD",
	"X_KEYWORD",
	"NOIDS_ATTR_KEYWORD",
	"SQSTRING",
	"DQSTRING",
	"'$'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:99

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 39

var yyAct = [...]int{

	3, 31, 9, 17, 10, 8, 4, 5, 11, 18,
	32, 13, 30, 33, 19, 20, 21, 28, 15, 22,
	26, 20, 21, 12, 27, 29, 25, 20, 21, 6,
	14, 34, 2, 24, 23, 16, 7, 1, 35,
}
var yyPact = [...]int{

	28, -1000, -2, -3, -1000, 21, -9, 15, -1000, -1000,
	-2, 25, -9, 5, -1000, -1000, -1000, -1000, -2, -1000,
	-1000, -1000, 11, -2, 9, -1000, -1000, -4, 1, 8,
	-2, -1000, -1000, -1000, 17, -1000,
}
var yyPgo = [...]int{

	0, 37, 36, 5, 35, 34, 33, 3, 0,
}
var yyR1 = [...]int{

	0, 1, 8, 8, 7, 7, 5, 5, 6, 6,
	4, 4, 4, 4, 3, 3, 2, 2,
}
var yyR2 = [...]int{

	0, 7, 0, 1, 1, 1, 1, 5, 1, 3,
	1, 5, 1, 5, 1, 3, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, 4, -8, 8, 10, 8, -2, -3, 11,
	13, -8, 8, -8, 5, -3, -4, -7, 4, 9,
	10, 11, -8, -5, -6, -7, 9, -8, 8, -8,
	16, 5, 9, 5, -8, -7,
}
var yyDef = [...]int{

	0, -2, 2, 0, 3, 0, 0, 2, 16, 14,
	2, 0, 3, 0, 1, 17, 15, 10, 2, 12,
	4, 5, 0, 2, 2, 6, 8, 0, 3, 0,
	2, 11, 9, 13, 0, 7,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 16, 3, 3, 3,
	4, 5, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 6, 3, 7,
}
var yyTok2 = [...]int{

	2, 3, 8, 9, 10, 11, 12, 13, 14, 15,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.y:28
		{
			yyVAL.genericSchema = yyDollar[5].genericSchema
			yyVAL.genericSchema.NumericOID = yyDollar[3].text
			yylex.(*schemaLexer).result = yyVAL.genericSchema
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:37
		{
			yyVAL.text = yyDollar[1].text
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:40
		{
			yyVAL.text = yyDollar[1].text
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:44
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, OIDsRule)
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:47
		{
			yyVAL.parameterizedKeyword = yyDollar[1].parameterizedKeyword
			yyVAL.parameterizedKeyword.addParameter(yyDollar[5].text)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:52
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, NumberIDsRule)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:55
		{
			yyVAL.parameterizedKeyword = yyDollar[1].parameterizedKeyword
			yyVAL.parameterizedKeyword.addParameter(yyDollar[3].text)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:60
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, OIDsRule)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:63
		{
			yyVAL.parameterizedKeyword = yyDollar[3].parameterizedKeyword
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:66
		{
			yyVAL.parameterizedKeyword = newParameterizedKeywordWithParameter(yyDollar[1].text, NumberIDsRule)
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:69
		{
			yyVAL.parameterizedKeyword = yyDollar[3].parameterizedKeyword
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:82
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addFlagKeywords(yyDollar[1].text)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:86
		{
			yyVAL.genericSchema = newGenericSchema()
			yyVAL.genericSchema.addParameterizedKeyword(yyDollar[1].text, yyDollar[3].parameterizedKeyword)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:91
		{
			yyVAL.genericSchema = yyDollar[1].genericSchema
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:94
		{
			yyDollar[1].genericSchema.add(yyDollar[3].genericSchema)
			yyVAL.genericSchema = yyDollar[1].genericSchema
		}
	}
	goto yystack /* stack new state and value */
}
